// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Chat struct {
	ID       string
	ChatName string
	ChatIcon string
	ChatType int64
}

type ChatMember struct {
	ChatID string
	UserID string
	Role   int64
}

type ChatMessage struct {
	ID          string
	MessageType int64
	MessageText string
	Time        string
	ChatID      string
	UserID      string
}

type Session struct {
	ID           string
	RefreshToken string
	AccessToken  string
	UserID       string
}

type User struct {
	ID          string
	Firstname   string
	Lastname    string
	Username    string
	Alias       sql.NullString
	Email       string
	Password    string
	PhoneNumber string
	BirthDate   string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}
