// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
;

INSERT INTO user (
    id,
    firstname,
    lastname,
    username,
    alias,
    email,
    password,
    phone_number,
    birth_date,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID          string
	Firstname   string
	Lastname    string
	Username    string
	Alias       sql.NullString
	Email       string
	Password    string
	PhoneNumber string
	BirthDate   string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Username,
		arg.Alias,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.BirthDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE user SET 
    deleted_at = ?
WHERE id = ?
`

type DeleteUserParams struct {
	DeletedAt sql.NullString
	ID        string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.DeletedAt, arg.ID)
	return err
}

const getUser = `-- name: GetUser :one
;

select id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
from user
where user.email = ? or user.username = ?
`

type GetUserParams struct {
	Email    string
	Username string
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
from user
where user.id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE user SET
    email = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
`

type UpdateEmailParams struct {
	Email     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateEmail, arg.Email, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE user SET
    password = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
`

type UpdatePasswordParams struct {
	Password  string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.Password, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE user SET
    firstname = ?,
    lastname = ?,
    alias = ?,
    birth_date = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Firstname string
	Lastname  string
	Alias     sql.NullString
	BirthDate string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Firstname,
		arg.Lastname,
		arg.Alias,
		arg.BirthDate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE user SET
    username = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, firstname, lastname, username, alias, email, password, phone_number, birth_date, created_at, updated_at, deleted_at
`

type UpdateUsernameParams struct {
	Username  string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUsername, arg.Username, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Alias,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
